os: linux
language: shell
git:
  lfs_skip_smudge: true
before_install: 
  -  - git lfs pull
install: skip
script:
  
  - git lfs ls-files
  - git lfs version

jobs:
  include:
   # - dist: xenial
    - dist: bionic
    - dist: focal
   # - dist: jammy
